kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sec-automation
nodes:
- role: control-plane
  extraPortMappings:
  # Yelb App
  - containerPort: 30000
    hostPort: 8080
    protocol: TCP
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker